#
# DreamLink Router Node. 
# Offers basic functions to support the network, recommended for devices with limited resources.
#

version: "3.7"

networks: 
  dreamlink:
    name: dreamlink

services:
  router:
    build: ../../images/ipfs
    image: dreamnettech/ipfs
    container_name: dreamlink
    restart: unless-stopped
    environment:
      IPFS_PROFILE: server,lowpower
      LIBP2P_FORCE_PNET: 1
      DREAMLINK_MODE: router
    networks: 
      - dreamlink
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
      - 8081:8081
    volumes:
      - ./data:/data/ipfs
